{{- if and .Values.containers (and (not .Values.cronjobs) (not .Values.function)) }}
{{- $hpa := .Values.hpa | default dict }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "name" $ }}
  namespace: {{ include "ns" $ }}
spec:
  minReplicas: {{ $hpa.min | default 1 }} 
  maxReplicas: {{ $hpa.max | default 1 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name" $ }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      {{- if $hpa.down }}
      - type: Pods
        value: {{ $hpa.down }}
        periodSeconds: 60
      {{- end }}
    scaleUp:
      stabilizationWindowSeconds: 15
      selectPolicy: Max
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
  metrics:
{{- if or (empty $hpa.scale) (eq ($hpa.scale | default "") "%") }}
  {{- if or $hpa.cpu (and (not (hasKey $hpa "cpu")) (not (hasKey $hpa "memory"))) }}
  - type: Resource
    resource:
      name: cpu
      target: 
        type: 'Utilization'
        averageUtilization: {{ $hpa.cpu | default 80 }}
  {{- end }}
  {{- if $hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target: 
        type: 'Utilization'
        averageUtilization: {{ $hpa.memory }}
  {{- end }}
{{- end }}
{{- if eq ($hpa.scale | default "") "#" }}
  {{- if or $hpa.cpu (and (not (hasKey $hpa "cpu")) (not (hasKey $hpa "memory"))) }}
  - type: Resource
    resource:
      name: cpu
      target: 
        type: 'Value'
        averageValue: {{ $hpa.cpu | default "1000" }}m
  {{- end }}
  {{- if $hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target: 
        type: 'Value'
        averageValue: {{ $hpa.memory }}Mi
  {{- end }}
{{- end }}
{{- end }}